import { existsSync, readFileSync } from "node:fs";
import { basename, extname, join, resolve } from "node:path";
import { createHash } from "node:crypto";
import { prisma } from "./prisma";

type Doc = Record<string, any>;
const source = resolve(process.argv[2] ?? "");
if (!source || !existsSync(source)) throw new Error("Usage: npm run migrate:cloudbase -- <export-directory>");
const report: Record<string, { read: number; migrated: number; skipped: number }> = {};
function load(name: string): Doc[] {
  const paths = [join(source, `${name}.json`), join(source, `${name}.jsonl`), join(source, name, "data.json")];
  const path = paths.find(existsSync); if (!path) return [];
  const raw = readFileSync(path, "utf8").trim(); if (!raw) return [];
  const parsed = extname(path) === ".jsonl" ? raw.split(/\r?\n/).map((line) => JSON.parse(line)) : JSON.parse(raw);
  return Array.isArray(parsed) ? parsed : parsed.data ?? [];
}
function date(value: any): Date | undefined { if (!value) return undefined; const raw = value.$date ?? value; const parsed = new Date(raw); return Number.isNaN(parsed.getTime()) ? undefined : parsed; }
function id(doc: Doc): string { return String(doc._id ?? doc.id); }
function metric(name: string, read: number, migrated: number) { report[name] = { read, migrated, skipped: read - migrated }; }
function role(value: any): "TEACHER" | "GUARDIAN" { return String(value).toLowerCase().includes("teacher") ? "TEACHER" : "GUARDIAN"; }

async function migrate() {
  const users = load("users"); let count = 0;
  for (const item of users) { if (!item._id) continue; await prisma.user.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), displayName: item.nickname ?? item.name ?? item.account ?? "迁移用户", avatarUrl: item.avatarUrl, roles: { create: { role: role(item.role) } }, ...(item._openid ? { identities: { create: { provider: "WECHAT", providerSubject: item._openid, verifiedAt: date(item.createTime) ?? new Date() } } } : {}) } }).catch(() => undefined); count++; } metric("users", users.length, count);
  let fallback = await prisma.user.findFirst({ where: { roles: { some: { role: "ADMIN" } } } });
  if (!fallback) fallback = await prisma.user.create({ data: { displayName: "迁移管理员", roles: { create: { role: "ADMIN" } } } });
  const students = load("students"); count = 0;
  for (const item of students) { const creator = item.parentId ?? item.teacherId ?? fallback.id; if (!await prisma.user.findUnique({ where: { id: creator } })) continue; await prisma.student.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), createdByUserId: creator, name: item.name ?? "未命名学生", gender: item.gender, grade: item.grade, status: item.status ?? "active" } }); if (item.parentId && await prisma.user.findUnique({ where: { id: item.parentId } })) await prisma.studentGuardian.upsert({ where: { studentId_guardianUserId: { studentId: id(item), guardianUserId: item.parentId } }, update: {}, create: { studentId: id(item), guardianUserId: item.parentId, relationship: "家长", isPrimary: true } }); count++; } metric("students", students.length, count);
  const courses = load("courses"); count = 0;
  for (const item of courses) { const teacherId = item.teacherId ?? fallback.id; if (!await prisma.user.findUnique({ where: { id: teacherId } })) continue; await prisma.course.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), teacherId, name: item.name ?? "迁移课程", subject: item.subject, description: item.description, status: item.status ?? "active" } }); count++; } metric("courses", courses.length, count);
  const classes = load("classes"); count = 0;
  for (const item of classes) { const teacherId = item.teacherId ?? fallback.id; if (!await prisma.user.findUnique({ where: { id: teacherId } })) continue; const courseId = item.courseId && await prisma.course.findUnique({ where: { id: item.courseId } }) ? item.courseId : undefined; await prisma.classroom.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), teacherId, courseId, name: item.name ?? "迁移班级", classType: String(item.classType).toLowerCase().includes("one") ? "ONE_ON_ONE" : "SMALL_GROUP", billingMode: String(item.billingMode).toLowerCase() === "cash" ? "CASH" : "PREPAID", status: "ACTIVE", inviteCode: item.inviteCode ?? `M${id(item).slice(-10)}`, location: item.location, scheduleRule: item.schedule ?? undefined } }); count++; } metric("classes", classes.length, count);
  const classMemberDocs = load("classMembers"), courseMemberDocs = load("courseMembers"), members = [...classMemberDocs, ...courseMemberDocs], migratedMembers = new Set<string>(); count = 0;
  for (const item of members) { if (!await prisma.classroom.findUnique({ where: { id: item.classId } }) || !await prisma.student.findUnique({ where: { id: item.studentId } })) continue; await prisma.classMember.upsert({ where: { classId_studentId: { classId: item.classId, studentId: item.studentId } }, update: {}, create: { id: id(item), classId: item.classId, studentId: item.studentId, status: String(item.status).toLowerCase() === "pending" ? "PENDING" : "APPROVED", totalHours: Number(item.totalHours ?? 0), consumedHours: Number(item.consumedHours ?? 0), remainingHours: Number(item.remainingHours ?? 0), pricePerHour: Number(item.pricePerHour ?? 0) } }); migratedMembers.add(id(item)); count++; }
  metric("classMembers", classMemberDocs.length, classMemberDocs.filter((item) => migratedMembers.has(id(item))).length);
  metric("courseMembers", courseMemberDocs.length, courseMemberDocs.filter((item) => migratedMembers.has(id(item))).length);
  const sessions = load("classSessions"); count = 0;
  for (const item of sessions) { if (!await prisma.classroom.findUnique({ where: { id: item.classId } })) continue; const startsAt = date(item.startsAt) ?? date(`${item.date}T${item.startTime}:00+08:00`); const endsAt = date(item.endsAt) ?? date(`${item.date}T${item.endTime}:00+08:00`); if (!startsAt || !endsAt) continue; await prisma.classSession.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), classId: item.classId, startsAt, endsAt, plannedHours: Number(item.totalHoursPlanned ?? item.plannedHours ?? 1), status: String(item.status).toLowerCase() === "completed" ? "COMPLETED" : String(item.status).toLowerCase() === "cancelled" ? "CANCELLED" : "SCHEDULED", source: String(item.source).toLowerCase() === "manual" ? "MANUAL" : "SCHEDULE", completedAt: date(item.completedTime) } }); count++; } metric("classSessions", sessions.length, count);
  const attendances = load("attendances"); count = 0;
  for (const item of attendances) { const sessionId = item.sessionId ?? item.scheduleId; const studentId = item.studentId; if (!sessionId || !studentId || !await prisma.classSession.findUnique({ where: { id: sessionId } }) || !await prisma.student.findUnique({ where: { id: studentId } })) continue; await prisma.sessionAttendance.upsert({ where: { sessionId_studentId: { sessionId, studentId } }, update: {}, create: { id: id(item), sessionId, studentId, status: String(item.status).toUpperCase().includes("LEAVE") ? "LEAVE" : String(item.status).toUpperCase().includes("ABSENT") ? "ABSENT" : "PRESENT", deductHours: Number(item.deductHours ?? item.classHours ?? 0), remark: item.remark ?? item.note } }); count++; } metric("attendances", attendances.length, count);

  const hours = load("classHours"); count = 0;
  for (const item of hours) { const member = item.memberId ? await prisma.classMember.findUnique({ where: { id: item.memberId } }) : await prisma.classMember.findFirst({ where: { classId: item.classId, studentId: item.studentId } }); if (!member) continue; const operatorId = await prisma.user.findUnique({ where: { id: item.operatorId ?? item.teacherId ?? "" } }) ? (item.operatorId ?? item.teacherId) : fallback.id; const raw = Number(item.delta ?? item.hours ?? item.change ?? 0); const kind = String(item.type ?? item.operation ?? "ADJUST").toUpperCase(); const delta = kind.includes("CONSUM") || kind.includes("DEDUCT") ? -Math.abs(raw) : kind.includes("REFUND") ? -Math.abs(raw) : raw; await prisma.hourLedgerEntry.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), memberId: member.id, studentId: member.studentId, sessionId: item.sessionId && await prisma.classSession.findUnique({ where: { id: item.sessionId } }) ? item.sessionId : undefined, operatorId, type: kind.includes("RECHARGE") ? "RECHARGE" : kind.includes("CONSUM") || kind.includes("DEDUCT") ? "CONSUME" : kind.includes("REFUND") ? "REFUND" : kind.includes("UNDO") ? "UNDO" : "ADJUST", delta, balanceAfter: Number(item.balanceAfter ?? item.remainingHours ?? member.remainingHours), idempotencyKey: item.idempotencyKey ?? `legacy-hour:${id(item)}`, remark: item.remark ?? item.reason, createdAt: date(item.createdAt ?? item.createTime) } }); count++; } metric("classHours", hours.length, count);

  const homeworks = load("homeworks"); count = 0;
  for (const item of homeworks) { const classId = item.classId ?? item.courseId; const classroom = classId ? await prisma.classroom.findUnique({ where: { id: classId } }) : null; if (!classroom) continue; const authorId = await prisma.user.findUnique({ where: { id: item.authorId ?? item.teacherId ?? "" } }) ? (item.authorId ?? item.teacherId) : classroom.teacherId; await prisma.homework.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), classId, authorId, title: item.title ?? "迁移作业", content: item.content ?? item.description ?? "", dueAt: date(item.dueAt ?? item.deadline), status: String(item.status).toUpperCase() === "DRAFT" ? "DRAFT" : String(item.status).toUpperCase() === "CLOSED" ? "CLOSED" : "PUBLISHED", attachments: (item.attachments ?? item.files) as never, createdAt: date(item.createdAt ?? item.createTime) } }); count++; } metric("homeworks", homeworks.length, count);

  const submissions = [...load("homework_submissions"), ...load("homeworkSubmissions")]; count = 0;
  for (const item of submissions) { const homeworkId = item.homeworkId; const studentId = item.studentId; if (!homeworkId || !studentId || !await prisma.homework.findUnique({ where: { id: homeworkId } }) || !await prisma.student.findUnique({ where: { id: studentId } })) continue; await prisma.homeworkSubmission.upsert({ where: { homeworkId_studentId: { homeworkId, studentId } }, update: {}, create: { id: id(item), homeworkId, studentId, content: item.content ?? item.answer, attachments: (item.attachments ?? item.files) as never, status: String(item.status).toUpperCase().includes("RETURN") ? "RETURNED" : item.reviewedAt || item.score != null ? "REVIEWED" : "SUBMITTED", score: item.score == null ? undefined : Number(item.score), comment: item.comment ?? item.feedback, submittedAt: date(item.submittedAt ?? item.createTime) ?? new Date(), reviewedAt: date(item.reviewedAt) } }); count++; } metric("homework_submissions", submissions.length, count);

  const materials = load("materials"); count = 0;
  for (const item of materials) { const uploaderId = await prisma.user.findUnique({ where: { id: item.uploaderId ?? item.teacherId ?? item.userId ?? "" } }) ? (item.uploaderId ?? item.teacherId ?? item.userId) : fallback.id; const classId = item.classId && await prisma.classroom.findUnique({ where: { id: item.classId } }) ? item.classId : undefined; await prisma.material.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), classId, uploaderId, name: item.name ?? item.fileName ?? "迁移资料", objectKey: item.objectKey ?? item.fileID ?? item.fileId ?? `legacy/${id(item)}`, mimeType: item.mimeType ?? "application/octet-stream", sizeBytes: Number(item.sizeBytes ?? item.size ?? 0), category: item.category, createdAt: date(item.createdAt ?? item.createTime) } }); count++; } metric("materials", materials.length, count);

  const plans = load("studyPlans"); count = 0;
  for (const item of plans) { const ownerUserId = await prisma.user.findUnique({ where: { id: item.ownerUserId ?? item.userId ?? item.parentId ?? "" } }) ? (item.ownerUserId ?? item.userId ?? item.parentId) : fallback.id; const studentId = item.studentId && await prisma.student.findUnique({ where: { id: item.studentId } }) ? item.studentId : undefined; await prisma.studyPlan.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), ownerUserId, studentId, title: item.title ?? item.name ?? "迁移计划", description: item.description ?? item.content, frequency: item.frequency as never, startsAt: date(item.startsAt ?? item.startDate), endsAt: date(item.endsAt ?? item.endDate), status: String(item.status).toUpperCase().includes("COMPLETE") ? "COMPLETED" : String(item.status).toUpperCase().includes("ARCHIVE") ? "ARCHIVED" : "ACTIVE", createdAt: date(item.createdAt ?? item.createTime) } }); count++; } metric("studyPlans", plans.length, count);

  const checkins = [...load("plan_checkins"), ...load("planCheckins")]; count = 0;
  for (const item of checkins) { const planId = item.planId; if (!planId || !await prisma.studyPlan.findUnique({ where: { id: planId } })) continue; await prisma.planCheckIn.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), planId, note: item.note ?? item.content, checkedAt: date(item.checkedAt ?? item.createTime) ?? new Date() } }); count++; } metric("plan_checkins", checkins.length, count);

  const mistakes = load("mistakes"); count = 0;
  for (const item of mistakes) { const ownerUserId = await prisma.user.findUnique({ where: { id: item.ownerUserId ?? item.userId ?? item.parentId ?? "" } }) ? (item.ownerUserId ?? item.userId ?? item.parentId) : fallback.id; const studentId = item.studentId && await prisma.student.findUnique({ where: { id: item.studentId } }) ? item.studentId : undefined; await prisma.mistake.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), ownerUserId, studentId, subject: item.subject, title: item.title ?? item.question ?? "迁移错题", content: item.content ?? item.question, answer: item.answer, analysis: item.analysis, tags: Array.isArray(item.tags) ? item.tags.map(String) : [], images: item.images as never, masteredAt: item.mastered ? date(item.updatedAt) ?? new Date() : date(item.masteredAt), createdAt: date(item.createdAt ?? item.createTime) } }); count++; } metric("mistakes", mistakes.length, count);

  const points = load("points_records"); count = 0;
  for (const item of points) { const userId = item.userId ?? item.parentId; if (!userId || !await prisma.user.findUnique({ where: { id: userId } })) continue; await prisma.pointLedgerEntry.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), userId, delta: Number(item.delta ?? item.points ?? 0), reason: item.reason ?? item.type ?? "历史积分", idempotencyKey: `legacy-point:${id(item)}`, createdAt: date(item.createdAt ?? item.createTime) } }); count++; } metric("points_records", points.length, count);
  const growth = load("user_growth"); count = 0;
  for (const item of growth) { const userId = item.userId; if (!userId || !await prisma.user.findUnique({ where: { id: userId } })) continue; const delta = Number(item.totalPoints ?? item.points ?? 0); if (delta) await prisma.pointLedgerEntry.upsert({ where: { idempotencyKey: `legacy-growth:${id(item)}` }, update: {}, create: { userId, delta, reason: "历史成长积分汇总", idempotencyKey: `legacy-growth:${id(item)}`, createdAt: date(item.updatedAt ?? item.createTime) } }); count++; } metric("user_growth", growth.length, count);

  const notifications = load("notifications"); count = 0;
  for (const item of notifications) { const userId = item.userId ?? item.receiverId; if (!userId || !await prisma.user.findUnique({ where: { id: userId } })) continue; await prisma.notification.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), userId, type: item.type ?? "LEGACY", title: item.title ?? "历史通知", body: item.body ?? item.content ?? "", resourceType: item.resourceType, resourceId: item.resourceId, dedupeKey: `legacy-notification:${id(item)}`, readAt: item.isRead || item.read ? date(item.readAt) ?? new Date() : date(item.readAt), createdAt: date(item.createdAt ?? item.createTime) } }); count++; } metric("notifications", notifications.length, count);

  const announcements = load("announcements"); count = 0;
  for (const item of announcements) { const authorId = await prisma.user.findUnique({ where: { id: item.authorId ?? item.userId ?? "" } }) ? (item.authorId ?? item.userId) : fallback.id; await prisma.announcement.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), authorId, title: item.title ?? "历史公告", content: item.content ?? "", audience: item.audience as never, publishedAt: date(item.publishedAt ?? item.createTime) ?? new Date(), expiresAt: date(item.expiresAt), createdAt: date(item.createdAt ?? item.createTime) } }); count++; } metric("announcements", announcements.length, count);

  const feedbacks = load("feedbacks"); count = 0;
  for (const item of feedbacks) { const userId = item.userId; if (!userId || !await prisma.user.findUnique({ where: { id: userId } })) continue; await prisma.feedback.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), userId, category: item.category ?? item.type ?? "历史反馈", content: item.content ?? "", contact: item.contact, attachments: item.attachments as never, status: String(item.status).toUpperCase().includes("RESOLV") ? "RESOLVED" : "OPEN", reply: item.reply, createdAt: date(item.createdAt ?? item.createTime) } }); count++; } metric("feedbacks", feedbacks.length, count);

  const manual = load("manualCourses"); count = 0;
  for (const item of manual) { const userId = item.userId; const startsAt = date(item.startsAt ?? item.startTime); const endsAt = date(item.endsAt ?? item.endTime); if (!userId || !startsAt || !endsAt || !await prisma.user.findUnique({ where: { id: userId } })) continue; await prisma.manualCourse.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), userId, name: item.name ?? item.title ?? "历史日程", startsAt, endsAt, location: item.location, note: item.note } }); count++; } metric("manualCourses", manual.length, count);

  const security = load("contentSecurityLogs"); count = 0;
  for (const item of security) { const userId = item.userId && await prisma.user.findUnique({ where: { id: item.userId } }) ? item.userId : undefined; await prisma.contentSecurityLog.upsert({ where: { id: id(item) }, update: {}, create: { id: id(item), userId, contentType: item.contentType ?? item.type ?? "text", contentHash: item.contentHash ?? `legacy:${id(item)}`, result: item.result ?? "UNKNOWN", provider: item.provider ?? "WECHAT_LEGACY", providerCode: item.providerCode, metadata: item.metadata as never, checkedAt: date(item.checkedAt ?? item.createTime) } }); count++; } metric("contentSecurityLogs", security.length, count);

  const activation = load("activation_codes"); count = 0;
  for (const item of activation) { const rawCode = item.codeHash ?? item.code; if (!rawCode) continue; const codeHash = item.codeHash ?? createHash("sha256").update(String(rawCode)).digest("hex"); await prisma.activationCode.upsert({ where: { codeHash }, update: {}, create: { id: id(item), codeHash, grant: (item.grant ?? { legacyType: item.type }) as never, expiresAt: date(item.expiresAt), usedAt: date(item.usedAt), createdAt: date(item.createdAt ?? item.createTime) } }); count++; } metric("activation_codes", activation.length, count);

  const payments = load("payments"); count = 0;
  for (const item of payments) { const orderId = item.orderId; if (!orderId || !await prisma.courseOrder.findUnique({ where: { id: orderId } })) continue; const providerTransactionId = item.providerTransactionId ?? item.transactionId ?? `legacy-payment:${id(item)}`; await prisma.paymentTransaction.upsert({ where: { providerTransactionId }, update: {}, create: { id: id(item), orderId, provider: item.provider ?? item.paymentMethod ?? "LEGACY", providerTransactionId, status: String(item.status).toUpperCase().includes("REFUND") ? "REFUNDED" : String(item.status).toUpperCase().includes("FAIL") ? "FAILED" : "SUCCEEDED", amountCents: Number(item.amountCents ?? Math.round(Number(item.amount ?? 0) * 100)), rawPayload: item as never, occurredAt: date(item.occurredAt ?? item.createTime) ?? new Date() } }); count++; } metric("payments", payments.length, count);

  console.log(JSON.stringify({ source, report, note: "All 24 legacy collections are mapped. Skipped rows are records whose required parent relation is absent; review the per-collection counts before cutover. Plaintext legacy passwords are intentionally never migrated." }, null, 2));
}
migrate().finally(() => prisma.$disconnect());
